import Head from "next/head";
import AbstractLines from "../components/ablines";
import Q2Logo from "../components/q2brand";

export default function Home() {
  return (
    <>
      <Head>
        <title>Q2 Capital Partners</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`q2--gradient`}>
        <section className="flex h-screen relative overflow-hidden justify-center items-center">
          <AbstractLines className="absolute w-screen opacity-40" />

          <Q2Logo className="w-[38vw] inline-block" />
        </section>
      </main>
    </>
  );
}
