import Head from "next/head";
import AbstractLines from "../components/ablines";
import Q2Logo from "../components/q2brand";

export default function Home() {
  return (
    <>
      <Head>
        <title>Q2 Capital Partners</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`q2--gradient`}>
        <section className="flex h-screen relative overflow-hidden justify-center items-center">
          <div className=" w-screen h-[300px] bg--300 flex justify-center relative items-center">
            <AbstractLines className="absolute md:top-[-25%] lg:top-[-50%] xl:top-[-75%] 2xl:top-[-90%] object-fill hidden md:inline-block w-screen opacity-40" />

            <Q2Logo className="w-[80vw] md:w-[38vw] inline-block" />
          </div>
        </section>
      </main>
    </>
  );
}
